[package]
name = "eyebright"
authors = ["Michael Greenberg <michael@greenberg.science>"]
description = "Manage backlight brightness on Intel displays"
license = "GPL-3.0"
version = "1.0.0"
edition = "2021"